name: Ingest (Telegram Bot Poll)

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch: {}

jobs:
  poll:
    runs-on: ubuntu-latest

    concurrency:
      group: ingest-bot-poll
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run bot poll
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          ALLOWED_CHAT_IDS: ${{ vars.ALLOWED_CHAT_IDS }}  # можно удалить, если не используешь
        run: |
          python app/ingest_bot_poll.py
